# 1. Create a 3x3x3 array with random values 

In [10]:
import numpy as np
import random
array = np.array([random.sample(range(10,30),3),random.sample(range(30,60),3),random.sample(range(60,90),3)])
print(array)

[[11 18 13]
 [42 35 47]
 [77 75 72]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
array = np.array([[0,0,0,0,0],[1,0,0,0,0],[1,2,0,0,0],[1,2,3,0,0],[1,2,3,0,0],[1,2,3,4,0]])
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [24]:
import numpy as np
array_8_8 = np.zeros((8,8),dtype=int)
array_8_8[::2,::2]=1
array_8_8[1::2,1::2]=1
print(array_8_8)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [35]:
array = np.random.random((5,5))
print(array)
array_min, array_max = array.min(),array.max()
print(array_min,array_max)
array = array - array_min /(array_max - array_min)
print("---AFTER NORMALIZATION ---")
print(array)

[[0.1191749  0.70516844 0.92162711 0.92425269 0.08911452]
 [0.62235215 0.96360166 0.9570395  0.26457377 0.93437144]
 [0.52267455 0.33512767 0.54371588 0.18149528 0.14197312]
 [0.71237956 0.40989082 0.40812059 0.14709654 0.45988073]
 [0.71904269 0.53329789 0.36824992 0.44779535 0.2226298 ]]
0.08911452220654192 0.9636016593532514
---AFTER NORMALIZATION ---
[[ 0.01727     0.60326354  0.81972222  0.82234779 -0.01279038]
 [ 0.52044725  0.86169676  0.8551346   0.16266887  0.83246655]
 [ 0.42076965  0.23322277  0.44181098  0.07959038  0.04006822]
 [ 0.61047466  0.30798592  0.3062157   0.04519164  0.35797583]
 [ 0.61713779  0.431393    0.26634502  0.34589045  0.1207249 ]]


# 5.  How to find common values between two arrays?

In [56]:
Z1 = np.random.randint(0,20,10)
print(Z1)
Z2 = np.random.randint(0,20,10)
print(Z2)
print(np.intersect1d(Z1,Z2))

[ 0 11  3  1  8  5  6 17  3 17]
[ 3  1  7  8  7 12 11  6 10 10]
[ 1  3  6  8 11]


# 6.How to get the dates of yesterday, today and tomorrow?

In [57]:
import datetime

today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print("TODAY : ", today)
print("YESTERDAY : ", yesterday)
print("TOMORROW : ", tomorrow)

TODAY :  2020-08-18
YESTERDAY :  2020-08-17
TOMORROW :  2020-08-19


# 7. Consider two random array A and B, check if they are equal

In [72]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [95]:
Z = np.random.random(10)
print(Z)
Z[Z.argmax()] = 0
print(Z)

[0.66036511 0.7942239  0.22904475 0.94665151 0.23976927 0.11386044
 0.34793226 0.97757604 0.83857695 0.6955041 ]
[0.66036511 0.7942239  0.22904475 0.94665151 0.23976927 0.11386044
 0.34793226 0.         0.83857695 0.6955041 ]


# 9. How to print all the values of an array?

In [97]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [98]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[-0.25296634  0.20758613  0.01539349 -0.2788872  -0.52688159  0.15696923
   0.11478281  0.25518253  0.18978446  0.11903649]
 [-0.31618732  0.3487186  -0.52140887  0.41756414 -0.27240699 -0.04038697
   0.1372625  -0.08215654  0.04591858  0.28308287]
 [ 0.0257884   0.38235016 -0.20916558 -0.03304764 -0.08197782  0.1180229
  -0.30910513 -0.05786373 -0.04701127  0.21200972]
 [-0.22825562  0.12996503 -0.15046087  0.02560797  0.18893593  0.16184785
   0.00647918 -0.37730748 -0.17927597  0.42246397]
 [ 0.32944899  0.03349044 -0.30285652 -0.33627342 -0.09734409  0.33019512
  -0.22561211  0.46606676  0.21523807 -0.41235323]]
[[-0.25296634  0.20758613  0.01539349 -0.2788872  -0.52688159  0.15696923
   0.11478281  0.25518253  0.18978446  0.11903649]
 [-0.31618732  0.3487186  -0.52140887  0.41756414 -0.27240699 -0.04038697
   0.1372625  -0.08215654  0.04591858  0.28308287]
 [ 0.0257884   0.38235016 -0.20916558 -0.03304764 -0.08197782  0.1180229
  -0.30910513 -0.05786373 -0.04701127  0.21200972]
 

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [99]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 2. 3. 6. 2. 3. 4. 2. 3. 1.]


In [100]:
np.add.at(Z, I, 1)
print(Z)

[ 7.  3.  5. 11.  3.  5.  7.  3.  5.  1.]


# 12.How to get the diagonal of a dot product?

In [101]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.95356947 0.3695933  0.32202127 0.73148606 0.43484531]
 [0.2999362  0.58710845 0.2290718  0.81473721 0.48349097]
 [0.23229864 0.261587   0.08620578 0.57315367 0.33142678]
 [0.3410863  0.44326368 0.70094993 0.90520419 0.5444956 ]
 [0.28979959 0.75543542 0.47309675 0.69760989 0.72500812]]
[[0.3289367  0.79305058 0.27818035 0.59473965 0.94556292]
 [0.15840777 0.75621676 0.13153116 0.55077242 0.90869473]
 [0.28031473 0.30281316 0.63793661 0.35890714 0.0014926 ]
 [0.34165934 0.13523558 0.75212142 0.0816839  0.74489412]
 [0.23455654 0.49788303 0.03639224 0.3536916  0.56305646]]
diagonal of a dot product method 1 is.... [0.8143926  1.1021152  0.5971641  0.96509502 1.88905608]
diagonal of a dot product method 2 is.... [0.8143926  1.1021152  0.5971641  0.96509502 1.88905608]


# 13.How to find the most frequent value in an array?

In [102]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[4 7 9 7 9 6 0 5 5 9 6 6 0 2 9 6 1 7 1 9 9 2 3 9 2 0 9 6 9 9 6 5 9 6 9 1 1
 3 4 7 2 1 9 9 4 8 5 2 1 1]
9


# 14.How to get the n largest values of an array

In [103]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [104]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
